/**
 * This class is generated by jOOQ
 */
package edu.ysu.msr17.commitloader.data;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>travistorrent</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, org.jooq.types.ULong> IDENTITY_DATA_COMMITS = Identities0.IDENTITY_DATA_COMMITS;
	public static final org.jooq.Identity<edu.ysu.msr17.commitloader.data.tables.records.DataUsersRecord, org.jooq.types.UInteger> IDENTITY_DATA_USERS = Identities0.IDENTITY_DATA_USERS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataBuildsCondensedRecord> KEY_DATA_BUILDS_CONDENSED_GH_PROJECT_NAME__GIT_TRIGGER_COMMIT = UniqueKeys0.KEY_DATA_BUILDS_CONDENSED_GH_PROJECT_NAME__GIT_TRIGGER_COMMIT;
	public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> KEY_DATA_COMMITS_PRIMARY = UniqueKeys0.KEY_DATA_COMMITS_PRIMARY;
	public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> KEY_DATA_COMMITS_DATA_COMMITS__REPO_SHA = UniqueKeys0.KEY_DATA_COMMITS_DATA_COMMITS__REPO_SHA;
	public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord> KEY_DATA_JSON_PRIMARY = UniqueKeys0.KEY_DATA_JSON_PRIMARY;
	public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataUsersRecord> KEY_DATA_USERS_PRIMARY = UniqueKeys0.KEY_DATA_USERS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, edu.ysu.msr17.commitloader.data.tables.records.DataUsersRecord> FK_DATA_COMMITS__AUTHOR = ForeignKeys0.FK_DATA_COMMITS__AUTHOR;
	public static final org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, edu.ysu.msr17.commitloader.data.tables.records.DataUsersRecord> FK_DATA_COMMITS__COMMITTER = ForeignKeys0.FK_DATA_COMMITS__COMMITTER;
	public static final org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord, edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> FK_DATA_JSON__ID = ForeignKeys0.FK_DATA_JSON__ID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, org.jooq.types.ULong> IDENTITY_DATA_COMMITS = createIdentity(edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS.ID);
		public static org.jooq.Identity<edu.ysu.msr17.commitloader.data.tables.records.DataUsersRecord, org.jooq.types.UInteger> IDENTITY_DATA_USERS = createIdentity(edu.ysu.msr17.commitloader.data.tables.DataUsers.DATA_USERS, edu.ysu.msr17.commitloader.data.tables.DataUsers.DATA_USERS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataBuildsCondensedRecord> KEY_DATA_BUILDS_CONDENSED_GH_PROJECT_NAME__GIT_TRIGGER_COMMIT = createUniqueKey(edu.ysu.msr17.commitloader.data.tables.DataBuildsCondensed.DATA_BUILDS_CONDENSED, edu.ysu.msr17.commitloader.data.tables.DataBuildsCondensed.DATA_BUILDS_CONDENSED.GH_PROJECT_NAME, edu.ysu.msr17.commitloader.data.tables.DataBuildsCondensed.DATA_BUILDS_CONDENSED.GIT_TRIGGER_COMMIT);
		public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> KEY_DATA_COMMITS_PRIMARY = createUniqueKey(edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS.ID);
		public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> KEY_DATA_COMMITS_DATA_COMMITS__REPO_SHA = createUniqueKey(edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS.REPO, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS.SHA);
		public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord> KEY_DATA_JSON_PRIMARY = createUniqueKey(edu.ysu.msr17.commitloader.data.tables.DataJson.DATA_JSON, edu.ysu.msr17.commitloader.data.tables.DataJson.DATA_JSON.ID);
		public static final org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataUsersRecord> KEY_DATA_USERS_PRIMARY = createUniqueKey(edu.ysu.msr17.commitloader.data.tables.DataUsers.DATA_USERS, edu.ysu.msr17.commitloader.data.tables.DataUsers.DATA_USERS.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, edu.ysu.msr17.commitloader.data.tables.records.DataUsersRecord> FK_DATA_COMMITS__AUTHOR = createForeignKey(edu.ysu.msr17.commitloader.data.Keys.KEY_DATA_USERS_PRIMARY, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS.AUTHOR);
		public static final org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, edu.ysu.msr17.commitloader.data.tables.records.DataUsersRecord> FK_DATA_COMMITS__COMMITTER = createForeignKey(edu.ysu.msr17.commitloader.data.Keys.KEY_DATA_USERS_PRIMARY, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS.COMMITTER);
		public static final org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord, edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> FK_DATA_JSON__ID = createForeignKey(edu.ysu.msr17.commitloader.data.Keys.KEY_DATA_COMMITS_PRIMARY, edu.ysu.msr17.commitloader.data.tables.DataJson.DATA_JSON, edu.ysu.msr17.commitloader.data.tables.DataJson.DATA_JSON.ID);
	}
}
