/**
 * This class is generated by jOOQ
 */
package edu.ysu.msr17.commitloader.data;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in travistorrent
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table travistorrent.data_commits
	 */
	public static final edu.ysu.msr17.commitloader.data.tables.DataCommits DATA_COMMITS = edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS;

	/**
	 * The table travistorrent.data_json
	 */
	public static final edu.ysu.msr17.commitloader.data.tables.DataJson DATA_JSON = edu.ysu.msr17.commitloader.data.tables.DataJson.DATA_JSON;

	/**
	 * The table travistorrent.data_users
	 */
	public static final edu.ysu.msr17.commitloader.data.tables.DataUsers DATA_USERS = edu.ysu.msr17.commitloader.data.tables.DataUsers.DATA_USERS;

	/**
	 * The table travistorrent.travistorrent_6_12_2016
	 */
	public static final edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016 TRAVISTORRENT_6_12_2016 = edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016.TRAVISTORRENT_6_12_2016;
}
