/**
 * This class is generated by jOOQ
 */
package edu.ysu.msr17.commitloader.data;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Travistorrent extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1248048465;

	/**
	 * The singleton instance of <code>travistorrent</code>
	 */
	public static final Travistorrent TRAVISTORRENT = new Travistorrent();

	/**
	 * No further instances allowed
	 */
	private Travistorrent() {
		super("travistorrent");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			edu.ysu.msr17.commitloader.data.tables.DataBuildsCondensed.DATA_BUILDS_CONDENSED,
			edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS,
			edu.ysu.msr17.commitloader.data.tables.DataJson.DATA_JSON,
			edu.ysu.msr17.commitloader.data.tables.DataUsers.DATA_USERS,
			edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016.TRAVISTORRENT_6_12_2016);
	}
}
