/**
 * This class is generated by jOOQ
 */
package edu.ysu.msr17.commitloader.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataBuildsCondensedRecord extends org.jooq.impl.TableRecordImpl<edu.ysu.msr17.commitloader.data.tables.records.DataBuildsCondensedRecord> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1530901861;

	/**
	 * Setter for <code>travistorrent.data_builds_condensed.gh_project_name</code>.
	 */
	public DataBuildsCondensedRecord setGhProjectName(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>travistorrent.data_builds_condensed.gh_project_name</code>.
	 */
	public java.lang.String getGhProjectName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>travistorrent.data_builds_condensed.git_trigger_commit</code>.
	 */
	public DataBuildsCondensedRecord setGitTriggerCommit(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>travistorrent.data_builds_condensed.git_trigger_commit</code>.
	 */
	public java.lang.String getGitTriggerCommit() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return edu.ysu.msr17.commitloader.data.tables.DataBuildsCondensed.DATA_BUILDS_CONDENSED.GH_PROJECT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return edu.ysu.msr17.commitloader.data.tables.DataBuildsCondensed.DATA_BUILDS_CONDENSED.GIT_TRIGGER_COMMIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getGhProjectName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getGitTriggerCommit();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DataBuildsCondensedRecord value1(java.lang.String value) {
		setGhProjectName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DataBuildsCondensedRecord value2(java.lang.String value) {
		setGitTriggerCommit(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DataBuildsCondensedRecord values(java.lang.String value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DataBuildsCondensedRecord
	 */
	public DataBuildsCondensedRecord() {
		super(edu.ysu.msr17.commitloader.data.tables.DataBuildsCondensed.DATA_BUILDS_CONDENSED);
	}

	/**
	 * Create a detached, initialised DataBuildsCondensedRecord
	 */
	public DataBuildsCondensedRecord(java.lang.String ghProjectName, java.lang.String gitTriggerCommit) {
		super(edu.ysu.msr17.commitloader.data.tables.DataBuildsCondensed.DATA_BUILDS_CONDENSED);

		setValue(0, ghProjectName);
		setValue(1, gitTriggerCommit);
	}
}
