/**
 * This class is generated by jOOQ
 */
package edu.ysu.msr17.commitloader.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataCommits extends org.jooq.impl.TableImpl<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> {

	private static final long serialVersionUID = 1276702649;

	/**
	 * The singleton instance of <code>travistorrent.data_commits</code>
	 */
	public static final edu.ysu.msr17.commitloader.data.tables.DataCommits DATA_COMMITS = new edu.ysu.msr17.commitloader.data.tables.DataCommits();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> getRecordType() {
		return edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord.class;
	}

	/**
	 * The column <code>travistorrent.data_commits.id</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>travistorrent.data_commits.repo</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.lang.String> REPO = createField("repo", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>travistorrent.data_commits.sha</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.lang.String> SHA = createField("sha", org.jooq.impl.SQLDataType.CHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>travistorrent.data_commits.message</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.data_commits.author</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, org.jooq.types.UInteger> AUTHOR = createField("author", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

	/**
	 * The column <code>travistorrent.data_commits.author_date</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.sql.Timestamp> AUTHOR_DATE = createField("author_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>travistorrent.data_commits.committer</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, org.jooq.types.UInteger> COMMITTER = createField("committer", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

	/**
	 * The column <code>travistorrent.data_commits.commit_date</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.sql.Timestamp> COMMIT_DATE = createField("commit_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>travistorrent.data_commits.verified</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.lang.Byte> VERIFIED = createField("verified", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>travistorrent.data_commits.verified_reason</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.lang.String> VERIFIED_REASON = createField("verified_reason", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>travistorrent.data_commits.added</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, org.jooq.types.UInteger> ADDED = createField("added", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaulted(true), this, "");

	/**
	 * The column <code>travistorrent.data_commits.removed</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, org.jooq.types.UInteger> REMOVED = createField("removed", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaulted(true), this, "");

	/**
	 * The column <code>travistorrent.data_commits.ss_gen_positive</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.lang.Byte> SS_GEN_POSITIVE = createField("ss_gen_positive", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>travistorrent.data_commits.ss_gen_negative</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.lang.Byte> SS_GEN_NEGATIVE = createField("ss_gen_negative", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>travistorrent.data_commits.ss_gen_neutral</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, java.lang.Byte> SS_GEN_NEUTRAL = createField("ss_gen_neutral", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * Create a <code>travistorrent.data_commits</code> table reference
	 */
	public DataCommits() {
		this("data_commits", null);
	}

	/**
	 * Create an aliased <code>travistorrent.data_commits</code> table reference
	 */
	public DataCommits(java.lang.String alias) {
		this(alias, edu.ysu.msr17.commitloader.data.tables.DataCommits.DATA_COMMITS);
	}

	private DataCommits(java.lang.String alias, org.jooq.Table<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> aliased) {
		this(alias, aliased, null);
	}

	private DataCommits(java.lang.String alias, org.jooq.Table<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.ysu.msr17.commitloader.data.Travistorrent.TRAVISTORRENT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, org.jooq.types.ULong> getIdentity() {
		return edu.ysu.msr17.commitloader.data.Keys.IDENTITY_DATA_COMMITS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord> getPrimaryKey() {
		return edu.ysu.msr17.commitloader.data.Keys.KEY_DATA_COMMITS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord>>asList(edu.ysu.msr17.commitloader.data.Keys.KEY_DATA_COMMITS_PRIMARY, edu.ysu.msr17.commitloader.data.Keys.KEY_DATA_COMMITS_DATA_COMMITS__REPO_SHA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataCommitsRecord, ?>>asList(edu.ysu.msr17.commitloader.data.Keys.FK_DATA_COMMITS__AUTHOR, edu.ysu.msr17.commitloader.data.Keys.FK_DATA_COMMITS__COMMITTER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.ysu.msr17.commitloader.data.tables.DataCommits as(java.lang.String alias) {
		return new edu.ysu.msr17.commitloader.data.tables.DataCommits(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.ysu.msr17.commitloader.data.tables.DataCommits rename(java.lang.String name) {
		return new edu.ysu.msr17.commitloader.data.tables.DataCommits(name, null);
	}
}
