/**
 * This class is generated by jOOQ
 */
package edu.ysu.msr17.commitloader.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataJson extends org.jooq.impl.TableImpl<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord> {

	private static final long serialVersionUID = 1245960801;

	/**
	 * The singleton instance of <code>travistorrent.data_json</code>
	 */
	public static final edu.ysu.msr17.commitloader.data.tables.DataJson DATA_JSON = new edu.ysu.msr17.commitloader.data.tables.DataJson();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord> getRecordType() {
		return edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord.class;
	}

	/**
	 * The column <code>travistorrent.data_json.id</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>travistorrent.data_json.data</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord, java.lang.String> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * Create a <code>travistorrent.data_json</code> table reference
	 */
	public DataJson() {
		this("data_json", null);
	}

	/**
	 * Create an aliased <code>travistorrent.data_json</code> table reference
	 */
	public DataJson(java.lang.String alias) {
		this(alias, edu.ysu.msr17.commitloader.data.tables.DataJson.DATA_JSON);
	}

	private DataJson(java.lang.String alias, org.jooq.Table<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord> aliased) {
		this(alias, aliased, null);
	}

	private DataJson(java.lang.String alias, org.jooq.Table<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.ysu.msr17.commitloader.data.Travistorrent.TRAVISTORRENT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord> getPrimaryKey() {
		return edu.ysu.msr17.commitloader.data.Keys.KEY_DATA_JSON_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord>>asList(edu.ysu.msr17.commitloader.data.Keys.KEY_DATA_JSON_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<edu.ysu.msr17.commitloader.data.tables.records.DataJsonRecord, ?>>asList(edu.ysu.msr17.commitloader.data.Keys.FK_DATA_JSON__ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.ysu.msr17.commitloader.data.tables.DataJson as(java.lang.String alias) {
		return new edu.ysu.msr17.commitloader.data.tables.DataJson(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.ysu.msr17.commitloader.data.tables.DataJson rename(java.lang.String name) {
		return new edu.ysu.msr17.commitloader.data.tables.DataJson(name, null);
	}
}
