/**
 * This class is generated by jOOQ
 */
package edu.ysu.msr17.commitloader.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Travistorrent_6_12_2016 extends org.jooq.impl.TableImpl<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record> {

	private static final long serialVersionUID = 1961619896;

	/**
	 * The singleton instance of <code>travistorrent.travistorrent_6_12_2016</code>
	 */
	public static final edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016 TRAVISTORRENT_6_12_2016 = new edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record> getRecordType() {
		return edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record.class;
	}

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_build_id</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> TR_BUILD_ID = createField("tr_build_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_project_name</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GH_PROJECT_NAME = createField("gh_project_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_is_pr</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> GH_IS_PR = createField("gh_is_pr", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_pr_created_at</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GH_PR_CREATED_AT = createField("gh_pr_created_at", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_pull_req_num</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_PULL_REQ_NUM = createField("gh_pull_req_num", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_lang</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GH_LANG = createField("gh_lang", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_merged_with</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GIT_MERGED_WITH = createField("git_merged_with", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_branch</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GIT_BRANCH = createField("git_branch", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_num_commits_in_push</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_NUM_COMMITS_IN_PUSH = createField("gh_num_commits_in_push", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_commits_in_push</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GH_COMMITS_IN_PUSH = createField("gh_commits_in_push", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_prev_commit_resolution_status</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GIT_PREV_COMMIT_RESOLUTION_STATUS = createField("git_prev_commit_resolution_status", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_prev_built_commit</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GIT_PREV_BUILT_COMMIT = createField("git_prev_built_commit", org.jooq.impl.SQLDataType.CHAR.length(40), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_prev_build</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> TR_PREV_BUILD = createField("tr_prev_build", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_first_commit_created_at</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.sql.Timestamp> GH_FIRST_COMMIT_CREATED_AT = createField("gh_first_commit_created_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_team_size</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_TEAM_SIZE = createField("gh_team_size", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_all_built_commits</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GIT_ALL_BUILT_COMMITS = createField("git_all_built_commits", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_num_all_built_commits</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GIT_NUM_ALL_BUILT_COMMITS = createField("git_num_all_built_commits", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_trigger_commit</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GIT_TRIGGER_COMMIT = createField("git_trigger_commit", org.jooq.impl.SQLDataType.CHAR.length(40), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_virtual_merged_into</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_VIRTUAL_MERGED_INTO = createField("tr_virtual_merged_into", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_original_commit</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_ORIGINAL_COMMIT = createField("tr_original_commit", org.jooq.impl.SQLDataType.CHAR.length(40), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_num_issue_comments</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_NUM_ISSUE_COMMENTS = createField("gh_num_issue_comments", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_num_commit_comments</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_NUM_COMMIT_COMMENTS = createField("gh_num_commit_comments", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_num_pr_comments</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_NUM_PR_COMMENTS = createField("gh_num_pr_comments", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_diff_src_churn</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GIT_DIFF_SRC_CHURN = createField("git_diff_src_churn", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.git_diff_test_churn</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GIT_DIFF_TEST_CHURN = createField("git_diff_test_churn", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_diff_files_added</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DIFF_FILES_ADDED = createField("gh_diff_files_added", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_diff_files_deleted</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DIFF_FILES_DELETED = createField("gh_diff_files_deleted", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_diff_files_modified</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DIFF_FILES_MODIFIED = createField("gh_diff_files_modified", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_diff_tests_added</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DIFF_TESTS_ADDED = createField("gh_diff_tests_added", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_diff_tests_deleted</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DIFF_TESTS_DELETED = createField("gh_diff_tests_deleted", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_diff_src_files</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DIFF_SRC_FILES = createField("gh_diff_src_files", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_diff_doc_files</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DIFF_DOC_FILES = createField("gh_diff_doc_files", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_diff_other_files</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DIFF_OTHER_FILES = createField("gh_diff_other_files", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_num_commits_on_files_touched</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_NUM_COMMITS_ON_FILES_TOUCHED = createField("gh_num_commits_on_files_touched", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_sloc</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_SLOC = createField("gh_sloc", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_test_lines_per_kloc</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> GH_TEST_LINES_PER_KLOC = createField("gh_test_lines_per_kloc", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_test_cases_per_kloc</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> GH_TEST_CASES_PER_KLOC = createField("gh_test_cases_per_kloc", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_asserts_cases_per_kloc</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> GH_ASSERTS_CASES_PER_KLOC = createField("gh_asserts_cases_per_kloc", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_by_core_team_member</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> GH_BY_CORE_TEAM_MEMBER = createField("gh_by_core_team_member", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_description_complexity</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> GH_DESCRIPTION_COMPLEXITY = createField("gh_description_complexity", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_pushed_at</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> GH_PUSHED_AT = createField("gh_pushed_at", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.gh_build_started_at</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.sql.Timestamp> GH_BUILD_STARTED_AT = createField("gh_build_started_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_status</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_STATUS = createField("tr_status", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_duration</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> TR_DURATION = createField("tr_duration", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_jobs</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_JOBS = createField("tr_jobs", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_build_number</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> TR_BUILD_NUMBER = createField("tr_build_number", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_job_id</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> TR_JOB_ID = createField("tr_job_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_lan</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_LAN = createField("tr_log_lan", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_status</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_STATUS = createField("tr_log_status", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_setup_time</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Long> TR_LOG_SETUP_TIME = createField("tr_log_setup_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_analyzer</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_ANALYZER = createField("tr_log_analyzer", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_frameworks</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_FRAMEWORKS = createField("tr_log_frameworks", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_bool_tests_ran</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> TR_LOG_BOOL_TESTS_RAN = createField("tr_log_bool_tests_ran", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_bool_tests_failed</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> TR_LOG_BOOL_TESTS_FAILED = createField("tr_log_bool_tests_failed", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_num_tests_ok</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_NUM_TESTS_OK = createField("tr_log_num_tests_ok", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_num_tests_failed</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_NUM_TESTS_FAILED = createField("tr_log_num_tests_failed", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_num_tests_run</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_NUM_TESTS_RUN = createField("tr_log_num_tests_run", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_num_tests_skipped</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_NUM_TESTS_SKIPPED = createField("tr_log_num_tests_skipped", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_tests_failed</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.String> TR_LOG_TESTS_FAILED = createField("tr_log_tests_failed", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_testduration</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> TR_LOG_TESTDURATION = createField("tr_log_testduration", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>travistorrent.travistorrent_6_12_2016.tr_log_buildduration</code>.
	 */
	public final org.jooq.TableField<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record, java.lang.Double> TR_LOG_BUILDDURATION = createField("tr_log_buildduration", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * Create a <code>travistorrent.travistorrent_6_12_2016</code> table reference
	 */
	public Travistorrent_6_12_2016() {
		this("travistorrent_6_12_2016", null);
	}

	/**
	 * Create an aliased <code>travistorrent.travistorrent_6_12_2016</code> table reference
	 */
	public Travistorrent_6_12_2016(java.lang.String alias) {
		this(alias, edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016.TRAVISTORRENT_6_12_2016);
	}

	private Travistorrent_6_12_2016(java.lang.String alias, org.jooq.Table<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record> aliased) {
		this(alias, aliased, null);
	}

	private Travistorrent_6_12_2016(java.lang.String alias, org.jooq.Table<edu.ysu.msr17.commitloader.data.tables.records.Travistorrent_6_12_2016Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.ysu.msr17.commitloader.data.Travistorrent.TRAVISTORRENT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016 as(java.lang.String alias) {
		return new edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016 rename(java.lang.String name) {
		return new edu.ysu.msr17.commitloader.data.tables.Travistorrent_6_12_2016(name, null);
	}
}
